# sudo for docker
sudo: true
language: java
jdk:
 - openjdk10

services:
  - docker

# force update docker-ce since the manifest is still experimental
addons:
  apt:
    packages:
      - docker-ce

# Only clone the most recent commit.
git:
  depth: 1

cache:
  apt: true
  directories:
  - "$HOME/.cache"
  - ~/.m2

jobs:
  include:
    - stage: Test stage
      before_script: echo "coucou"
      script: echo "test 1"
      script: echo "test 2"
    - stage: Package
      script: echo "package this shit"