# binfmt_misc seems to act a bit weirdly on precise
dist: xenial
# sudo for docker
sudo: true
language: java
jdk:
 - openjdk8

services:
  - docker

# force update docker-ce since the manifest is still experimental
addons:
  apt:
    packages:
      - docker-ce

# Only clone the most recent commit.
git:
  depth: 1

cache:
  apt: true
  directories:
  - "$HOME/.cache"
  - ~/.m2

jobs:
  include:
    - stage: Test stage
      before_script: echo "coucou"
      script: echo "test 1"
      script: echo "test 2"

    - stage: docker-deploy
      # install binfmt to allow arm build on x86 (see https://dev.to/zeerorg/build-multi-arch-docker-images-on-travis-5428)
      before_install:
        - sudo docker run --privileged linuxkit/binfmt:v0.6
        - sudo docker run -d --privileged -p 1234:1234 --name buildkit moby/buildkit:latest --addr tcp://0.0.0.0:1234 --oci-worker-platform linux/amd64 --oci-worker-platform linux/armhf
        - sudo docker cp buildkit:/usr/bin/buildctl /usr/bin/
        - export BUILDKIT_HOST=tcp://0.0.0.0:1234
      # skill install step
      install: true
      script: JOAL_VERSION="" && PLATFORMS="linux/amd64,linux/arm,linux/arm64,linux/arm/v6" && buildctl build --frontend dockerfile.v0 --local dockerfile=. --local context=. --frontend-opt platform=${PLATFORMS} --frontend-opt filename=./Dockerfile --exporter image --exporter-opt name=docker.io/anthonyraymond/dumb_repository:${JOAL_VERSION} --exporter-opt push=true